### ISSUE TITLE
Vega Lite 5

### ISSUE THREAD

**Issue by wkrasnicki** [procyon-rs/vega_lite_4.rs#23]
Hi!

I am considering creating a similar crate for Vega Lite 5, mostly for my personal usage, but will of course share it if I succeed. I noticed that the approach you took in creating this crate, was to copy the vega_lite_3, regenerate the schema and then update the API. I am willing to do that for VL5, however I'm quite new to Rust and currently working on my first project for personal use (for which I need interactive graphs), so I'd like to ask you, how much effort would you say it took you to create this crate and more importantly do you have anything against me using yours?

Cheers

**Comment by ThomAub** [comment]
Yes this crate is mostly auto generated. We use some script to download the schema specification and with some `sed` magic we try to improve the rust API. 
Feel free to do the same and we can add it here or have a link to your version of the V5 specification.

**Comment by ThomAub** [comment]
I will create the repo for the crate as a copy of this current repo.
This should allow you to apply the same changes you have on you current branch. If this this ok with you I will find some time to do it this week ?

**Comment by ptiza** [comment]
> I will create the repo for the crate as a copy of this current repo. This should allow you to apply the same changes you have on you current branch. If this this ok with you I will find some time to do it this week ?

Sure, fine for me! Thanks

**Comment by davidB** [comment]
@ptiza Can you remade your PR on https://github.com/procyon-rs/vega_lite_5.rs, Please ?

**Comment by ptiza** [comment]
Opened https://github.com/procyon-rs/vega_lite_5.rs/pull/1

**Comment by davidB** [comment]
released on crates.io https://crates.io/crates/vega_lite_5

Thank you @ptiza

**Comment by RalfNorthman** [comment]
Nice!

I noticed the repository link on crates.io goes to vega_lite_4.
