### ISSUE TITLE
Feature request: support for pie charts

### ISSUE THREAD

**Issue by frp** [procyon-rs/vega_lite_4.rs#6]
Subj. Like this: https://vega.github.io/vega-lite/docs/arc.html#pie-and-donut-charts

Currently, Mark enum does not have Arc, and feeding JSON from the Vega Lite examples to vega_lite_4 fails too with "data did not match any variant of untagged enum AnyMark".

**Comment by ThomAub** [comment]
Hello :) 
You can find an first example with the Arc Mark. It's still rough and we might change the current generated builder naming. 
Hope it still can help a bit. Might add some other example from the documentation to test other properties.
