### ISSUE TITLE
New version with `ndarray` 0.14 dependency

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [procyon-rs/vega_lite_4.rs#8]
Could you release a new version that uses `ndarray` `0.14`? The current version `0.3.1` breaks if you use a current `ndarray` for populating the data field in this library. I've seen that you already changed it in the current master.

**Comment by ThomAub** [comment]
New version of the crate will be publish when issue like #9 will be fixed. 
It's under investigation 🕵️

**Comment by davidB** [comment]
version `0.5.0` is released with `ndarray-0.14`

reopen if you have issue
